### ISSUE TITLE
Seems addon no longer works with 20.*

### ISSUE THREAD

**Issue by mnerec** [xbmc-danish-addons/plugin.video.dr.dk.bonanza#9]
Installing this on the latest KODI release doesn't seem to work.

```2023-04-28 23:32:44.690 T:19108    info <general>: Starting Kodi (20.1 (20.1.0) Git:20230312-289ec664e3). Platform: Windows NT x86 64-bit
2023-04-28 23:32:44.690 T:19108    info <general>: Using Release Kodi x64
2023-04-28 23:32:44.690 T:19108    info <general>: Kodi compiled 2023-03-12 by MSVC 193431937 for Windows NT x86 64-bit version 10.0 (0x0A00000B)
2023-04-28 23:32:44.690 T:19108    info <general>: Running on Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.2846
<SNIP>
2023-04-28 23:33:17.464 T:6400    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.dr.dk.bonanza/
2023-04-28 23:33:17.466 T:19108   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dr.dk.bonanza/) failed
2023-04-28 23:33:24.984 T:19108   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-04-28 23:33:25.152 T:12268   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Tools\Kodi\portable_data\addons\plugin.video.dr.dk.bonanza\default.py", line 2, in <module>
                                                       from resources.lib import addon
                                                     File "C:\Tools\Kodi\portable_data\addons\plugin.video.dr.dk.bonanza\resources\lib\addon.py", line 27, in <module>
                                                       import buggalo
                                                     File "C:\Tools\Kodi\portable_data\addons\script.module.buggalo\lib\buggalo.py", line 56, in <module>
                                                       userflow.trackUserFlow('%s%s' % (sys.argv[0], sys.argv[2]))
                                                     File "C:\Tools\Kodi\portable_data\addons\script.module.buggalo\lib\buggalo_userflow.py", line 43, in trackUserFlow
                                                       userFlow = loadUserFlow()
                                                     File "C:\Tools\Kodi\portable_data\addons\script.module.buggalo\lib\buggalo_userflow.py", line 54, in loadUserFlow
                                                       path = xbmc.translatePath(BUGGALO_ADDON.getAddonInfo('profile'))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

**Comment by TermeHansen** [comment]
Right, thanks will update and push one of the next days.

**Comment by TermeHansen** [comment]
Actually, I think I already fixed it, but did not push to official repo. @mnerec  can you please try:
https://github.com/xbmc-danish-addons/plugin.video.dr.dk.bonanza/archive/refs/heads/master.zip
and see if it also works for you?

**Comment by mnerec** [comment]
The one from master works again!

**Comment by TermeHansen** [comment]
Thks, I will push to official repo and close this issue when done...

**Comment by TermeHansen** [comment]
Updated in official repo...

**Comment by mnerec** [comment]
Working, thanks!
